Repository WildCodeSchool/tours-0320-php-villa-corsica, pull requests merged in 2020-06, with the labels that each got.

#3 Navbar
  assets/fonts/snellbt-regular-webfont.eot
  assets/fonts/snellbt-regular-webfont.ttf
  assets/fonts/snellbt-regular-webfont.woff
  assets/fonts/snellbt-regular-webfont.woff2
  assets/images/home.jpg
  assets/images/logo.png
  assets/scss/_vars.scss
  assets/scss/app.scss
  templates/base.html.twig
  webpack.config.js
Labels: enhancement

#5 Make entity
  assets/scss/_vars.scss
  assets/scss/app.scss
  src/Entity/Admin.php
  src/Entity/GoldenBook.php
  src/Entity/Picture.php
  src/Entity/Villa.php
  src/Migrations/.gitignore
  src/Migrations/Version20200605074342.php
  src/Migrations/Version20200605074636.php
  src/Migrations/Version20200605074840.php
  src/Migrations/Version20200605075214.php
  src/Repository/AdminRepository.php
  src/Repository/GoldenBookRepository.php
  src/Repository/PictureRepository.php
  src/Repository/VillaRepository.php
Labels: enhancement

#6 Home page
  assets/scss/app.scss
  src/Controller/HomeController.php
  templates/base.html.twig
  templates/home/index.html.twig
Labels: enhancement

#8 Ajouter champe poster
  src/Entity/Villa.php
  src/Migrations/Version20200610083057.php
Labels: enhancement

#9 Consulter la liste des villas
  assets/images/chiara/poster.jpg
  assets/images/fiori1/poster.jpg
  assets/images/fiori2/poster.jpg
  assets/images/laura/poster.jpg
  assets/images/lea/poster.jpg
  assets/images/villas.jpg
  assets/images/villas2.jpg
  assets/scss/app.scss
  assets/scss/villaTab.scss
  package.json
  src/Controller/VillaController.php
  src/Migrations/Version20200610084345.php
  templates/base.html.twig
  templates/villa/index.html.twig
  templates/villa/show.html.twig
  yarn.lock
Labels: enhancement

#11 ajustement du css
  assets/scss/villaTab.scss
  templates/base.html.twig
  templates/home/index.html.twig
  templates/villa/index.html.twig
Labels: Reviewed, enhancement

#13 villa details
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/villadetails.scss
  templates/villa/show.html.twig
Labels: Reviewed

#14 Consulter la liste des villas
  assets/images/cover/home.jpg
  assets/images/cover/villas_list.jpg
  assets/images/villas.jpg
  assets/images/villas2.jpg
  templates/home/index.html.twig
  templates/villa/index.html.twig
Labels: Reviewed

#19 modifier nav bar
  templates/base.html.twig
Labels: Reviewed

#21 Consulter la liste des villas
  assets/scss/villaTab.scss
  templates/villa/index.html.twig
Labels: Reviewed

#23 link path on nav bar fixed, footer map changed
  templates/base.html.twig
Labels: Reviewed

#24 Dev
  Dockerfile
  assets/fonts/snellbt-regular-webfont.eot
  assets/fonts/snellbt-regular-webfont.ttf
  assets/fonts/snellbt-regular-webfont.woff
  assets/fonts/snellbt-regular-webfont.woff2
  assets/images/chiara/poster.jpg
  assets/images/cover/cofee.jpg
  assets/images/cover/home.jpg
  assets/images/cover/villas_list.jpg
  assets/images/fiori1/poster.jpg
  assets/images/fiori2/poster.jpg
  assets/images/laura/poster.jpg
  assets/images/lea/poster.jpg
  assets/images/logo.png
  assets/images/pages/activity/beach.jpg
  assets/images/pages/activity/corsica1.jpg
  assets/images/pages/activity/corsica2.jpg
  assets/images/pages/activity/corsica3.jpg
  assets/scss/_vars.scss
  assets/scss/activity.scss
  assets/scss/app.scss
  assets/scss/villaTab.scss
  assets/scss/villadetails.scss
  captain-definition
  docker-compose.yml
  docker-entry.sh
  nginx.conf
  package.json
  php.ini
  src/Controller/ActivityController.php
  src/Controller/HomeController.php
  src/Controller/VillaController.php
  src/Entity/Admin.php
  src/Entity/GoldenBook.php
  src/Entity/Picture.php
  src/Entity/Villa.php
  src/Migrations/.gitignore
  src/Migrations/Version20200618141219.php
  src/Repository/AdminRepository.php
  src/Repository/GoldenBookRepository.php
  src/Repository/PictureRepository.php
  src/Repository/VillaRepository.php
  symfony.lock
  templates/activity/index.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
  templates/villa/index.html.twig
  templates/villa/show.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#15 Formulairedereservation
  .env
  README.md
  assets/scss/villadetails.scss
  composer.json
  composer.lock
  config/packages/twig.yaml
  config/services.yaml
  src/Controller/VillaController.php
  src/Form/BookingType.php
  src/Model/Booking.php
  symfony.lock
  templates/base.html.twig
  templates/email/reservation.html.twig
  templates/villa/show.html.twig
Labels: Reviewed

#26 Fixing bug
  assets/images/cover/villas_list.jpg
  src/Migrations/Version20200622120751.php
  templates/activity/index.html.twig
  templates/villa/index.html.twig
Labels: Reviewed

#27 Pagecontact
  .gitignore
  assets/images/contact/backgroundpagecontact.jpg
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/contact.scss
  src/Controller/ContactController.php
  src/Form/ContactType.php
  src/Model/Contact.php
  templates/base.html.twig
  templates/contact/index.html.twig
  templates/email/message.html.twig
Labels: Reviewed

#28 ajouter des informations dans le footer
  assets/scss/app.scss
  templates/base.html.twig
Labels: Reviewed
